sudo: required
env:
  # Run tests in parellel, up to 5 at once
  - DEVICE=ios84 FINAL_GULP=coveralls
  - DEVICE=ios84 TEST=e2e/driver
  - DEVICE=ios84 TEST=e2e/testapp RECURSIVE=1
  - DEVICE=ios84 TEST=e2e/uicatalog RECURSIVE=1
  - DEVICE=ios84 TEST=e2e/safari RECURSIVE=1
language:
  - objective-c
osx_image: xcode6.4
before_install:
  # Instruments fix:
  # https://github.com/travis-ci/travis-ci/issues/4218
  - ./bin/instruments-auth.sh
before_script:
  - npm install
  - npm install -g gulp
  - npm install -g mocha
  - gulp transpile
  - gulp jshint
script:
  - if [ -n "$RECURSIVE" ]; then mocha --recursive build/test/$TEST -g @skip-ci -i; else mocha build/test/$TEST -g @skip-ci -i; fi
  - if [ -n "$FINAL_GULP" ]; then gulp $FINAL_GULP; fi
